### PR TITLE
Add mismatch plots

### PR DESCRIPTION
**Pull request by hyanwong**
This adds the code to generate the mismatch plots, and the preliminary Makefile to generate the data for them (takes a number of days to run!)

### CODE REVIEW

**Comment by awohns** [comment]
Looks good to me, are you happy for me to merge?

**Comment by hyanwong** [comment]
There's another plot that Jerome thought it good to add, with no error (I'm re-running it now due to a previous problem).

**Comment by awohns** [comment]
@hyanwong, is this merge-ready?

**Comment by hyanwong** [comment]
Not quite, sorry!

**Pull request merged**
